name: MaskUI
version: 1.1 BETA
main: SkulZOnTheYT\MaskUI\Main
api: 5.0.0
depend: BedrockEconomy
author: SkulZOnTheYT, Kylan1940

commands:
  mask:
   description: "open mask ui"
   permission: "maskui-open.commands"
   
permissions:
  maskui-open.commands:
   description: "allow user open mask ui"
   default: op

  maskui-skeleton.give:
   description: "allow givving mask skeleton into player"
   default: op

  maskui-zombie.give:
   description: "allow givving mask zombie into player"
   default: op

  maskui-creeper.give:
   description: "allow givving mask creeper into player"
   default: op

  maskui-wither.give:
   description: "allow givving mask wither into player"
   default: op

  maskui-steve.give:
   description: "allow givving mask steve into player"
   default: op

  maskui-dragon.give:
   description: "allow givving mask dragon into player"
   default: op
