name: MaskShopUI
version: 1.0
main: SkulZOnTheYT\MaskShopUI\Main
api: 5.0.0
author: SkulZOnTheYT, Kylan1940

commands:
  mask:
   description: open mask shop in ui
   usage: "/mask"
   aliases:
     - ms
   permission: mask.shop
  permissions:
   mask.shop:
    default: true
    description: allow user open mask shop
