name: MaskUI
version: 1.0
main: SkulZOnTheYT\MaskUI\Main
api: 5.0.0
author: SkulZOnTheYT, Kylan1940

commands:
  mask:
   description: "open mask ui"
   permission: "mask.ui"
permissions:
  mask.ui:
   description: "allow user open mask ui"
   default: op